# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/gym',
                'doc_host': 'https://flyswot.github.io',
                'git_url': 'https://github.com/flyswot/gym',
                'lib_path': 'gym'},
  'syms': {'gym.core': {'gym.core.foo': ('core.html#foo', 'gym/core.py')}}}
